language: android
git:
  depth: 3
jdk: oraclejdk8
android:
  components:
    - tools
    - android-27
    - build-tools
    - build-tools-27.0.3
    - ndk
    - extra-android-m2repository
    - platform-tools

  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

  
